### ISSUE TITLE
nanoc crashes with v4.2.0

### ISSUE THREAD

**Issue by mgr777** [gjtorikian/nanoc-conref-fs#5]
It seems that nanoc crashes with >v4.2.0 and nanoc-conref-fs.

#https://github.com/atom/flight-manual.atom.io/issues/205

**Comment by nuclearsandwich** [comment]
@mgr777 do you have an example stacktrace of the crash? I don't doubt that it does but when we try for a reproduction I'd like to be sure we're hitting the same issue.

It's a pretty busy week for me so I don't expect I'll get to this or #4 until late next week at the earliest.

**Comment by mgr777** [comment]
may be the crashlog helps? thank you!

`Crashlog created at 2016-06-16 12:20:59 +0200

===== MESSAGE:

TypeError: wrong argument type Class (expected Module)

===== COMPILATION STACK:

  (empty)

===== STACK TRACE:

  0. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-conref-fs-0.6.5/lib/nanoc-conref-fs/conref-fs.rb:5:in `include'
  1. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-conref-fs-0.6.5/lib/nanoc-conref-fs/conref-fs.rb:5:in `<class:ConrefFS>'
  2. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-conref-fs-0.6.5/lib/nanoc-conref-fs/conref-fs.rb:4:in `<top (required)>'
  3. C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  4. C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  5. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-conref-fs-0.6.5/lib/nanoc-conref-fs.rb:10:in `<top (required)>'
  6. C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  7. C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  8. lib/helpers.rb:1:in `<main>'
  9. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/base/entities/code_snippet.rb:31:in `eval'
  10. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/base/entities/code_snippet.rb:31:in `load'
  11. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/base/repos/site_loader.rb:24:in `each'
  12. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/base/repos/site_loader.rb:24:in `site_from_config'
  13. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/base/repos/site_loader.rb:12:in `new_from_cwd'
  14. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/command_runner.rb:24:in `site'
  15. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:156:in `site'
  16. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:161:in `compiler'
  17. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:166:in `stack'
  18. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:270:in `write_compilation_stack'
  19. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:116:in `write_compact_error'
  20. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:92:in `print_error'
  21. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:71:in `rescue in handle_while'
  22. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:45:in `handle_while'
  23. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  24. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/command_runner.rb:11:in `call'
  25. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  26. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  27. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  28. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  29. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/commands/nanoc.rb:37:in `block in define'
  30. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  31. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  32. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  33. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli.rb:53:in `block in run'
  34. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  35. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  36. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib/nanoc/cli.rb:51:in `run'
  37. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/bin/nanoc:9:in `<top (required)>'
  38. C:/Ruby22-x64/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

Nanoc 4.2.0 © 2007-2016 Denis Defreyne.
Running ruby 2.2.3 (2015-08-18) on x64-mingw32 with RubyGems 2.4.5.1.

===== SYSTEM INFORMATION:

MINGW32_NT-6.1 VCNOTE254 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

===== INSTALLED GEMS:

  activesupport 4.2.6
  addressable 2.4.0
  adsf 1.2.1
  asciidoctor 1.5.4
  bigdecimal 1.2.6
  bundler 1.12.5
  colored 1.2
  cri 2.7.0
  ethon 0.8.1, 0.9.0
  extended-markdown-filter 0.4.6, 0.4.7
  ffi 1.9.10
  gemoji 2.1.0
  html-pipeline 2.2.4
  html-pipeline-asciidoc_filter 1.5.3
  html-pipeline-rouge_filter 1.0.3, 1.0.4
  html-proofer 3.0.4, 3.0.6
  i18n 0.7.0
  io-console 0.4.3
  json 1.8.1, 1.8.3
  liquid 3.0.6
  mercenary 0.3.5, 0.3.6
  mini_portile2 2.0.0, 2.1.0
  minitest 5.4.3, 5.8.4, 5.9.0
  nanoc 4.2.0
  nanoc-conref-fs 0.6.5
  nanoc-html-pipeline 0.3.3
  nokogiri 1.6.7.2, 1.6.8
  parallel 1.6.2, 1.9.0
  pkg-config 1.1.7
  power_assert 0.2.2
  psych 2.0.8
  rack 1.6.4
  rake 10.4.2, 11.1.1, 11.2.2
  rdoc 4.2.0
  rouge 1.10.1, 1.11.1
  test-unit 3.0.8
  thread_safe 0.3.5
  typhoeus 0.8.0
  tzinfo 1.2.2
  yell 2.0.5, 2.0.6

===== GEMFILE.LOCK:

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    asciidoctor (1.5.4)
    colored (1.2)
    cri (2.7.0)
      colored (~> 1.2)
    ethon (0.9.0)
      ffi (>= 1.3.0)
    extended-markdown-filter (0.4.7)
      html-pipeline (~> 2.0)
      nokogiri (~> 1.6.4)
    ffi (1.9.10-x64-mingw32)
    gemoji (2.1.0)
    html-pipeline (2.2.4)
      activesupport (>= 2, < 5)
      nokogiri (>= 1.4)
    html-pipeline-asciidoc_filter (1.5.3)
      asciidoctor (~> 1.5.3)
      html-pipeline (~> 2.2.2)
    html-pipeline-rouge_filter (1.0.4)
      activesupport
      html-pipeline (>= 1.11)
      rouge (~> 1.8)
    html-proofer (3.0.6)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      colored (~> 1.2)
      mercenary (~> 0.3.2)
      nokogiri (~> 1.5)
      parallel (~> 1.3)
      typhoeus (~> 0.7)
      yell (~> 2.0)
    i18n (0.7.0)
    json (1.8.3)
    liquid (3.0.6)
    mercenary (0.3.6)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    nanoc (4.2.0)
      cri (~> 2.3)
    nanoc-conref-fs (0.6.5)
      activesupport (~> 4.2)
      liquid (~> 3.0)
      nanoc (~> 4.0)
    nanoc-html-pipeline (0.3.3)
      html-pipeline (~> 2.0)
      nanoc (>= 3.1, < 5.0)
    nokogiri (1.6.8-x64-mingw32)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    parallel (1.9.0)
    pkg-config (1.1.7)
    rake (11.2.2)
    rouge (1.11.1)
    thread_safe (0.3.5)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yell (2.0.6)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  activesupport (~> 4.2)
  extended-markdown-filter (~> 0.4)
  gemoji (= 2.1.0)
  html-pipeline-asciidoc_filter (~> 1.5)
  html-pipeline-rouge_filter (~> 1.0)
  html-proofer (~> 3.0)
  nanoc (~> 4.1)
  nanoc-conref-fs (~> 0.5)
  nanoc-html-pipeline (= 0.3.3)
  rake

RUBY VERSION
   ruby 2.2.3p173

BUNDLED WITH
   1.12.5

===== LOAD PATHS:

  0. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/colored-1.2/lib
  1. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib
  2. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-4.2.0/lib
  3. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib
  4. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib
  5. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib
  6. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib
  7. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib
  8. C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nanoc-conref-fs-0.6.5/lib
  9. C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0
  10. C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/x64-msvcrt
  11. C:/Ruby22-x64/lib/ruby/site_ruby
  12. C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0
  13. C:/Ruby22-x64/lib/ruby/vendor_ruby/2.2.0/x64-msvcrt
  14. C:/Ruby22-x64/lib/ruby/vendor_ruby
  15. C:/Ruby22-x64/lib/ruby/2.2.0
  16. C:/Ruby22-x64/lib/ruby/2.2.0/x64-mingw32
`

**Comment by gjtorikian** [comment]
Closed by https://github.com/gjtorikian/nanoc-conref-fs/pull/8
